"""
This type stub file was generated by pyright.
"""

from pymupdf import *
from pymupdf import __doc__, __version__, _as_fz_document, _as_fz_page, _as_pdf_document, _as_pdf_page, _g_out_message, _globals, _log_items, _log_items_active, _log_items_clear

