import os
import tempfile
import wave
from pathlib import Path

import pyttsx3
import pythoncom


def synthesize_speech(text: str) -> str:
    """
    Generate speech using Windows SAPI5 and save it as a WAV file.

    Returns:
        str: Absolute path to the generated WAV file.
    """

    text = (text or "").strip()

    if not text:
        raise ValueError(
            "TTS text cannot be empty."
        )

    # --------------------------------------------------------
    # INITIALIZE COM
    # --------------------------------------------------------
    #
    # IMPORTANT:
    # This function is called from asyncio.to_thread().
    # SAPI5 uses Windows COM, so initialize COM inside
    # the worker thread.
    #
    pythoncom.CoInitialize()

    output_path = None
    engine = None

    try:

        # ----------------------------------------------------
        # CREATE TEMPORARY OUTPUT PATH
        # ----------------------------------------------------

        fd, temp_name = tempfile.mkstemp(
            prefix="chatbot_tts_",
            suffix=".wav",
        )

        os.close(fd)

        output_path = Path(
            temp_name
        ).resolve()

        # Remove the empty file created by mkstemp.
        if output_path.exists():

            output_path.unlink()

        # ----------------------------------------------------
        # INITIALIZE WINDOWS SAPI5
        # ----------------------------------------------------

        engine = pyttsx3.init(
            driverName="sapi5"
        )

        # ----------------------------------------------------
        # GET AVAILABLE VOICES
        # ----------------------------------------------------

        voices = engine.getProperty(
            "voices"
        )

        if not voices:

            raise RuntimeError(
                "No Windows SAPI5 voices are installed."
            )

        # Use the first available Windows voice.
        engine.setProperty(
            "voice",
            voices[0].id,
        )

        # ----------------------------------------------------
        # TTS SETTINGS
        # ----------------------------------------------------

        engine.setProperty(
            "rate",
            175,
        )

        # Volume MUST be between 0.0 and 1.0.
        engine.setProperty(
            "volume",
            1.0,
        )

        # ----------------------------------------------------
        # GENERATE WAV
        # ----------------------------------------------------

        engine.save_to_file(
            text,
            str(output_path),
        )

        engine.runAndWait()

        # ----------------------------------------------------
        # STOP ENGINE
        # ----------------------------------------------------

        try:

            engine.stop()

        except Exception:

            pass

        engine = None

        # ----------------------------------------------------
        # CHECK FILE
        # ----------------------------------------------------

        if not output_path.exists():

            raise RuntimeError(
                "SAPI5 did not create the WAV file."
            )

        file_size = output_path.stat().st_size

        if file_size < 100:

            raise RuntimeError(
                "SAPI5 generated an empty or invalid WAV file."
            )

        # ----------------------------------------------------
        # VALIDATE WAV
        # ----------------------------------------------------

        try:

            with wave.open(
                str(output_path),
                "rb",
            ) as wav:

                channels = wav.getnchannels()
                sample_width = wav.getsampwidth()
                sample_rate = wav.getframerate()
                frame_count = wav.getnframes()

                if channels <= 0:

                    raise ValueError(
                        "WAV contains no audio channels."
                    )

                if sample_width <= 0:

                    raise ValueError(
                        "WAV has an invalid sample width."
                    )

                if sample_rate <= 0:

                    raise ValueError(
                        "WAV has an invalid sample rate."
                    )

                if frame_count <= 0:

                    raise ValueError(
                        "WAV contains no audio frames."
                    )

        except wave.Error as exc:

            raise RuntimeError(
                f"Invalid WAV generated by SAPI5: {exc}"
            ) from exc

        # ----------------------------------------------------
        # VERIFY RIFF/WAVE HEADER
        # ----------------------------------------------------

        with open(
            output_path,
            "rb",
        ) as audio_file:

            header = audio_file.read(12)

        if len(header) < 12:

            raise RuntimeError(
                "Generated WAV file is too small."
            )

        if header[0:4] != b"RIFF":

            raise RuntimeError(
                "Generated audio is not a RIFF file."
            )

        if header[8:12] != b"WAVE":

            raise RuntimeError(
                "Generated audio is not a WAVE file."
            )

        # ----------------------------------------------------
        # SUCCESS
        # ----------------------------------------------------

        return str(
            output_path
        )

    except Exception:

        # Clean up generated file if anything failed.

        if output_path is not None:

            try:

                output_path.unlink(
                    missing_ok=True
                )

            except Exception:

                pass

        raise

    finally:

        # Stop engine if an exception happened
        # before normal cleanup.

        if engine is not None:

            try:

                engine.stop()

            except Exception:

                pass

        # ----------------------------------------------------
        # RELEASE COM
        # ----------------------------------------------------

        try:

            pythoncom.CoUninitialize()

        except Exception:

            pass