import os
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Optional

import bcrypt
from jose import JWTError, jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer


# ============================================================
# CONFIGURATION
# ============================================================

SECRET_KEY = os.getenv(
    "JWT_SECRET_KEY",
    "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET",
)

ALGORITHM = "HS256"

ACCESS_TOKEN_EXPIRE_MINUTES = int(
    os.getenv(
        "ACCESS_TOKEN_EXPIRE_MINUTES",
        "60",
    )
)

security = HTTPBearer(
    auto_error=False
)


# ============================================================
# USER MODEL
# ============================================================

@dataclass
class User:
    user_id: str
    username: str
    role: str


# ============================================================
# PASSWORD
# ============================================================

def hash_password(password: str) -> str:
    """
    Hash a password using bcrypt.

    bcrypt supports passwords up to 72 bytes.
    Longer passwords are rejected instead of silently truncated.
    """

    password_bytes = password.encode("utf-8")

    if len(password_bytes) > 72:
        raise ValueError(
            "Password cannot be longer than 72 bytes."
        )

    hashed = bcrypt.hashpw(
        password_bytes,
        bcrypt.gensalt(),
    )

    return hashed.decode("utf-8")


def verify_password(
    plain_password: str,
    password_hash: str,
) -> bool:

    password_bytes = plain_password.encode("utf-8")

    if len(password_bytes) > 72:
        return False

    try:
        return bcrypt.checkpw(
            password_bytes,
            password_hash.encode("utf-8"),
        )

    except (ValueError, TypeError):
        return False


# ============================================================
# USERS
# ============================================================
#
# Development users.
#
# IMPORTANT:
# Replace these hashes with hashes generated by
# security/create_user.py.
#
# DO NOT store plaintext passwords in production.
#

USERS = {
    "admin": {
        "user_id": "admin-01",
        "username": "admin",
        "role": "admin",
        "password_hash": hash_password("Admin@123"),
    },

    "supervisor": {
        "user_id": "supervisor-01",
        "username": "supervisor",
        "role": "supervisor",
        "password_hash": hash_password("Supervisor@123"),
    },

    "user": {
        "user_id": "user-01",
        "username": "user",
        "role": "user",
        "password_hash": hash_password("User@123"),
    },
}


# ============================================================
# LOGIN
# ============================================================

def authenticate_user(
    username: str,
    password: str,
) -> Optional[User]:

    user_data = USERS.get(username)

    if not user_data:
        return None

    if not verify_password(
        password,
        user_data["password_hash"],
    ):
        return None

    return User(
        user_id=user_data["user_id"],
        username=user_data["username"],
        role=user_data["role"],
    )


# ============================================================
# JWT
# ============================================================

def create_access_token(
    user: User,
) -> str:

    now = datetime.now(timezone.utc)

    expire = now + timedelta(
        minutes=ACCESS_TOKEN_EXPIRE_MINUTES
    )

    payload = {
        "sub": user.user_id,
        "username": user.username,
        "role": user.role,
        "iat": int(now.timestamp()),
        "exp": int(expire.timestamp()),
    }

    return jwt.encode(
        payload,
        SECRET_KEY,
        algorithm=ALGORITHM,
    )


# ============================================================
# CURRENT USER
# ============================================================

def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(
        security
    ),
) -> User:

    if credentials is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required.",
            headers={
                "WWW-Authenticate": "Bearer"
            },
        )

    token = credentials.credentials

    try:

        payload = jwt.decode(
            token,
            SECRET_KEY,
            algorithms=[ALGORITHM],
        )

        user_id = payload.get("sub")
        username = payload.get("username")
        role = payload.get("role")

        if not user_id or not username or not role:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid authentication token.",
                headers={
                    "WWW-Authenticate": "Bearer"
                },
            )

        # ----------------------------------------------------
        # IMPORTANT
        # Never blindly trust role information from JWT.
        # Verify against server-side user record.
        # ----------------------------------------------------

        user_data = USERS.get(username)

        if not user_data:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="User no longer exists.",
                headers={
                    "WWW-Authenticate": "Bearer"
                },
            )

        if user_data["user_id"] != user_id:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid user identity.",
                headers={
                    "WWW-Authenticate": "Bearer"
                },
            )

        if user_data["role"] != role:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid user role.",
                headers={
                    "WWW-Authenticate": "Bearer"
                },
            )

        return User(
            user_id=user_id,
            username=username,
            role=role,
        )

    except HTTPException:
        raise

    except JWTError:

        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired authentication token.",
            headers={
                "WWW-Authenticate": "Bearer"
            },
        )